local Navic = {
		NavicIconsFile = {fg = C.fg, },
		NavicIconsModule = {fg = C.cyan, },
		NavicIconsNamespace = {fg = C.fg, },
		NavicIconsPackage = {fg = C.fg, },
		NavicIconsClass = {fg = C.cyan, },
		NavicIconsMethod = {fg = C.blue, },
		NavicIconsProperty = {fg = C.red, },
		NavicIconsField = {fg = C.red, },
		NavicIconsConstructor = {fg = C.cyan, },
		NavicIconsEnum = {fg = C.cyan, },
		NavicIconsInterface = {fg = C.cyan, },
		NavicIconsFunction = {fg = C.blue, },
		NavicIconsVariable = {fg = C.red, },
		NavicIconsConstant = {fg = C.orange, },
		NavicIconsString = {fg = C.green, },
		NavicIconsNumber = {fg = C.orange, },
		NavicIconsBoolean = {fg = C.orange, },
		NavicIconsArray = {fg = C.cyan, },
		NavicIconsObject = {fg = C.cyan, },
		NavicIconsKey = {fg = C.purple, },
		NavicIconsKeyword = {fg = C.purple, },
		NavicIconsNull = {fg = C.orange, },
		NavicIconsEnumMember = {fg = C.orange, },
		NavicIconsStruct = {fg = C.cyan, },
		NavicIconsEvent = {fg = C.yellow, },
		NavicIconsOperator = {fg = C.fg, },
		NavicIconsTypeParameter = {fg = C.red, },
		NavicText = {fg = C.context, },
		NavicSeparator = {fg = C.context, },
}

return Navic